CREATE TABLE `BOARD`
(
    `BOARD_CODE`    INT NOT NULL AUTO_INCREMENT
 COMMENT '게시글코드',
    `TITLE`    VARCHAR(40) NOT NULL COMMENT '제목',
    `POSTED_DATE`    VARCHAR(20) NOT NULL COMMENT '작성일시',
    `DELETE_DATE`    VARCHAR(20) COMMENT '삭제일시',
    `VIEW_COUNT`    INT DEFAULT 0 NOT NULL COMMENT '조회수',
    `BOARD_CONTENT`    VARCHAR(2000) NOT NULL COMMENT '게시글내용',
    `USER_ID`    VARCHAR(20) NOT NULL COMMENT '아이디',
 PRIMARY KEY ( `BOARD_CODE` )
) COMMENT = '게시판';


CREATE TABLE `COMMENT`
(
    `COMMENT_CODE`    INT NOT NULL AUTO_INCREMENT
 COMMENT '댓글번호',
    `COMMENT_CONTENT`    VARCHAR(600) NOT NULL COMMENT '댓글내용',
    `POSTED_DATE`    VARCHAR(20) NOT NULL COMMENT '작성일시',
    `DELETE_DATE`    VARCHAR(20) COMMENT '삭제일시',
    `BOARD_CODE`    INT NOT NULL COMMENT '게시글코드',
    `USER_ID`    VARCHAR(20) NOT NULL COMMENT '아이디',
 PRIMARY KEY ( `COMMENT_CODE` )
) COMMENT = '커뮤니티댓글';

CREATE UNIQUE INDEX `BOARD_COMMENT_PK` ON `BOARD_COMMENT`
( `COMMENT_CODE` ); 

CREATE TABLE `COMMENT`
(
    `COMMENT_CODE`    INT NOT NULL AUTO_INCREMENT
 COMMENT '댓글번호',
    `COMMENT_CONTENT`    VARCHAR(600) NOT NULL COMMENT '댓글내용',
    `POSTED_DATE`    VARCHAR(20) NOT NULL COMMENT '작성일시',
    `DELETE_DATE`    VARCHAR(20) COMMENT '삭제일시',
    `BOARD_CODE`    INT NOT NULL COMMENT '게시글코드',
    `USER_ID`    VARCHAR(20) NOT NULL COMMENT '아이디',
 PRIMARY KEY ( `COMMENT_CODE` )
) COMMENT = '커뮤니티댓글';

CREATE UNIQUE INDEX `COMMENT_PK` ON `COMMENT`
( `COMMENT_CODE` );
